name: Build Service
on: 
  push: 
    branches: [main]
jobs:
  pre-build:
    runs-on: ubuntu-latest
    outputs:
      service: ${{ steps.filter.outputs.changes }}

    steps:

    - name: Checkout
      uses: actions/checkout@v3


    - uses: dorny/paths-filter@v2
      id: filter
      with:
        base: ${{ github.ref }}
        filters: |
          user:
            - user/**
            - basic/**'
            - pom.xml
          gateway:
            - gateway/**
            - basic/**'
            - pom.xml  
          scheme:
            - scheme/**
            - basic/**'
            - pom.xml              


  build:

    needs: pre-build
    strategy:
      matrix:
        service: ${{ fromJSON(needs.pre-build.outputs.service) }}
    runs-on: ubuntu-latest

    steps:

    - name: echo
      run: |
        echo "构建${{ matrix.service }}"
        echo "${{ needs.pre-build.outputs.service }}"
        echo "${{ fromJSON(needs.pre-build.outputs.service) }}"   

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:

    - name: deploy
      run: echo success

    - name: deploy
      run: ping -c 4 ipv6.im.lazysun.me
